In [29]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [30]:
data = pd.read_csv("iris.csv")
data

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [31]:
data.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [32]:
data.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [33]:
x = data.iloc[:,:-1].values
y = data.iloc[:,2].values

In [34]:
from sklearn.preprocessing import LabelEncoder
ls = LabelEncoder()
Y = ls.fit_transform(y)

In [46]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state = 1)

In [47]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_train

array([[0.52941176, 0.41666667, 0.61016949, 0.54166667],
       [1.        , 0.41666667, 0.86440678, 0.91666667],
       [0.38235294, 0.20833333, 0.49152542, 0.41666667],
       [0.61764706, 0.33333333, 0.77966102, 0.83333333],
       [0.44117647, 0.33333333, 0.69491525, 0.95833333],
       [0.29411765, 0.70833333, 0.08474576, 0.04166667],
       [0.35294118, 0.125     , 0.50847458, 0.5       ],
       [0.26470588, 0.58333333, 0.06779661, 0.04166667],
       [0.64705882, 0.33333333, 0.61016949, 0.58333333],
       [0.70588235, 0.20833333, 0.81355932, 0.70833333],
       [0.73529412, 0.41666667, 0.76271186, 0.83333333],
       [0.23529412, 0.625     , 0.06779661, 0.08333333],
       [0.5       , 0.08333333, 0.6779661 , 0.58333333],
       [0.58823529, 0.375     , 0.77966102, 0.70833333],
       [0.67647059, 0.375     , 0.61016949, 0.5       ],
       [1.        , 0.25      , 1.        , 0.91666667],
       [0.41176471, 0.75      , 0.11864407, 0.08333333],
       [0.20588235, 0.66666667, 0.06779661, 0.04166667],
       [0.14705882, 0.41666667, 0.06779661, 0.08333333],
       [0.26470588, 0.29166667, 0.49152542, 0.54166667],
       [0.23529412, 0.58333333, 0.08474576, 0.04166667],
       [0.35294118, 0.625     , 0.05084746, 0.04166667],
       [1.        , 0.75      , 0.96610169, 0.875     ],
       [0.76470588, 0.45833333, 0.74576271, 0.83333333],
       [0.88235294, 0.375     , 0.89830508, 0.70833333],
       [0.61764706, 0.33333333, 0.77966102, 0.875     ],
       [0.55882353, 0.33333333, 0.6440678 , 0.70833333],
       [0.5       , 0.58333333, 0.59322034, 0.625     ],
       [1.        , 0.33333333, 0.96610169, 0.79166667],
       [0.41176471, 0.41666667, 0.54237288, 0.45833333],
       [0.14705882, 0.58333333, 0.10169492, 0.04166667],
       [0.41176471, 0.20833333, 0.6779661 , 0.79166667],
       [0.58823529, 0.29166667, 0.66101695, 0.70833333],
       [0.14705882, 0.41666667, 0.06779661, 0.        ],
       [0.11764706, 0.5       , 0.05084746, 0.04166667],
       [0.64705882, 0.41666667, 0.81355932, 0.875     ],
       [0.08823529, 0.58333333, 0.06779661, 0.08333333],
       [0.52941176, 0.41666667, 0.66101695, 0.70833333],
       [0.64705882, 0.5       , 0.69491525, 0.79166667],
       [0.70588235, 0.45833333, 0.57627119, 0.54166667],
       [0.41176471, 0.33333333, 0.59322034, 0.5       ],
       [0.70588235, 0.54166667, 0.79661017, 1.        ],
       [0.5       , 0.41666667, 0.6440678 , 0.70833333],
       [0.23529412, 0.75      , 0.10169492, 0.04166667],
       [0.5       , 0.08333333, 0.50847458, 0.375     ],
       [0.61764706, 0.375     , 0.55932203, 0.5       ],
       [0.64705882, 0.41666667, 0.76271186, 0.70833333],
       [0.20588235, 0.125     , 0.38983051, 0.375     ],
       [0.58823529, 0.54166667, 0.84745763, 1.        ],
       [0.35294118, 0.20833333, 0.50847458, 0.5       ],
       [0.32352941, 0.70833333, 0.08474576, 0.04166667],
       [0.17647059, 0.45833333, 0.08474576, 0.        ],
       [0.26470588, 0.875     , 0.08474576, 0.        ],
       [0.70588235, 0.54166667, 0.79661017, 0.83333333],
       [0.02941176, 0.41666667, 0.05084746, 0.04166667],
       [0.5       , 0.29166667, 0.69491525, 0.625     ],
       [0.61764706, 0.29166667, 0.72881356, 0.75      ],
       [0.47058824, 0.41666667, 0.69491525, 0.70833333],
       [0.26470588, 0.625     , 0.08474576, 0.04166667],
       [0.23529412, 0.54166667, 0.11864407, 0.16666667],
       [0.44117647, 0.29166667, 0.52542373, 0.375     ],
       [0.17647059, 0.45833333, 0.08474576, 0.        ],
       [0.91176471, 0.33333333, 0.86440678, 0.75      ],
       [0.55882353, 0.375     , 0.55932203, 0.5       ],
       [0.97058824, 0.41666667, 0.94915254, 0.83333333],
       [0.70588235, 0.41666667, 0.71186441, 0.91666667],
       [0.58823529, 0.125     , 0.57627119, 0.5       ],
       [0.55882353, 0.58333333, 0.74576271, 0.91666667],
       [0.85294118, 0.66666667, 0.86440678, 1.        ],
       [0.38235294, 0.375     , 0.44067797, 0.5       ],
       [0.41176471, 1.        , 0.08474576, 0.125     ],
       [0.44117647, 0.29166667, 0.49152542, 0.45833333],
       [0.05882353, 0.125     , 0.05084746, 0.08333333],
       [0.35294118, 0.16666667, 0.47457627, 0.41666667],
       [0.76470588, 0.45833333, 0.66101695, 0.58333333],
       [0.20588235, 0.58333333, 0.10169492, 0.125     ],
       [0.73529412, 0.33333333, 0.6440678 , 0.54166667],
       [0.20588235, 0.625     , 0.10169492, 0.20833333],
       [0.14705882, 0.58333333, 0.15254237, 0.04166667],
       [0.58823529, 0.58333333, 0.77966102, 0.95833333],
       [0.38235294, 0.33333333, 0.66101695, 0.79166667],
       [0.73529412, 0.5       , 0.83050847, 0.91666667],
       [0.20588235, 0.54166667, 0.06779661, 0.04166667],
       [0.23529412, 0.70833333, 0.08474576, 0.125     ],
       [0.47058824, 0.5       , 0.6440678 , 0.70833333],
       [0.08823529, 0.45833333, 0.08474576, 0.04166667],
       [0.44117647, 0.29166667, 0.69491525, 0.75      ],
       [0.14705882, 0.45833333, 0.10169492, 0.04166667],
       [0.64705882, 0.41666667, 0.71186441, 0.79166667],
       [0.17647059, 0.20833333, 0.59322034, 0.66666667],
       [0.08823529, 0.5       , 0.06779661, 0.04166667],
       [0.61764706, 0.5       , 0.72881356, 0.91666667],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.38235294, 0.41666667, 0.52542373, 0.5       ],
       [0.02941176, 0.375     , 0.06779661, 0.04166667],
       [0.35294118, 0.16666667, 0.45762712, 0.375     ],
       [0.20588235, 0.        , 0.42372881, 0.375     ],
       [0.23529412, 0.625     , 0.06779661, 0.04166667],
       [0.17647059, 0.41666667, 0.06779661, 0.04166667],
       [0.17647059, 0.16666667, 0.38983051, 0.375     ],
       [0.08823529, 0.66666667, 0.        , 0.04166667],
       [0.47058824, 0.41666667, 0.54237288, 0.58333333],
       [0.52941176, 0.375     , 0.62711864, 0.54166667],
       [0.20588235, 0.58333333, 0.08474576, 0.04166667],
       [0.70588235, 0.45833333, 0.62711864, 0.58333333],
       [0.41176471, 0.375     , 0.54237288, 0.5       ],
       [0.55882353, 0.08333333, 0.59322034, 0.58333333],
       [0.79411765, 0.5       , 0.62711864, 0.54166667],
       [0.44117647, 0.29166667, 0.69491525, 0.75      ],
       [0.32352941, 0.58333333, 0.11864407, 0.04166667],
       [0.20588235, 0.41666667, 0.10169492, 0.04166667],
       [0.52941176, 0.25      , 0.77966102, 0.54166667],
       [0.52941176, 0.33333333, 0.50847458, 0.5       ],
       [0.85294118, 0.41666667, 0.81355932, 0.625     ],
       [0.41176471, 0.25      , 0.42372881, 0.375     ],
       [0.58823529, 0.33333333, 0.69491525, 0.58333333],
       [0.61764706, 0.45833333, 0.76271186, 0.70833333],
       [0.58823529, 0.20833333, 0.66101695, 0.58333333],
       [0.70588235, 0.45833333, 0.77966102, 0.95833333],
       [0.17647059, 0.45833333, 0.08474576, 0.        ]])

In [48]:
x_test = scaler.transform(x_test)
x_test

array([[0.44117647, 0.83333333, 0.03389831, 0.04166667],
       [0.23529412, 0.20833333, 0.33898305, 0.41666667],
       [0.67647059, 0.41666667, 0.57627119, 0.54166667],
       [0.32352941, 0.79166667, 0.05084746, 0.125     ],
       [1.05882353, 0.75      , 0.91525424, 0.79166667],
       [0.58823529, 0.54166667, 0.62711864, 0.625     ],
       [0.76470588, 0.45833333, 0.69491525, 0.91666667],
       [0.23529412, 0.75      , 0.15254237, 0.125     ],
       [0.11764706, 0.5       , 0.10169492, 0.04166667],
       [0.76470588, 0.5       , 0.79661017, 0.91666667],
       [0.38235294, 0.29166667, 0.54237288, 0.5       ],
       [0.32352941, 0.79166667, 0.11864407, 0.125     ],
       [0.82352941, 0.41666667, 0.83050847, 0.83333333],
       [0.61764706, 0.5       , 0.59322034, 0.58333333],
       [0.5       , 0.375     , 0.59322034, 0.58333333],
       [0.02941176, 0.5       , 0.05084746, 0.04166667],
       [0.44117647, 0.25      , 0.50847458, 0.45833333],
       [0.38235294, 0.41666667, 0.59322034, 0.58333333],
       [0.32352941, 0.58333333, 0.08474576, 0.125     ],
       [0.20588235, 0.5       , 0.03389831, 0.04166667],
       [0.35294118, 0.25      , 0.57627119, 0.45833333],
       [0.32352941, 0.41666667, 0.59322034, 0.58333333],
       [0.70588235, 0.41666667, 0.6779661 , 0.66666667],
       [0.20588235, 0.625     , 0.05084746, 0.08333333],
       [0.85294118, 0.5       , 0.84745763, 0.70833333],
       [0.41176471, 0.33333333, 0.52542373, 0.5       ],
       [0.35294118, 0.91666667, 0.06779661, 0.04166667],
       [0.23529412, 0.75      , 0.08474576, 0.08333333],
       [0.52941176, 0.33333333, 0.62711864, 0.45833333],
       [0.58823529, 0.20833333, 0.6779661 , 0.75      ]])

In [55]:
from sklearn.neighbors import KNeighborsRegressor

knn_reg = KNeighborsRegressor(n_neighbors=10)
knn_reg.fit(x_train, y_train)

KNeighborsRegressor(n_neighbors=10)

In [57]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

# Print the metrics
print("Mean Absolute Error:", mae)
print("Mean Squared Error:", mse)

Mean Absolute Error: 0.18300000000000002
Mean Squared Error: 0.05549000000000004